export const IXC_SECTOR_OPTIONS = Object.freeze([
  ['63', 'TÉCNICO - AVARÉ'],
  ['41', 'TÉCNICO - ITAPORANGA'],
  ['61', 'TÉCNICO - OSASCO'],
  ['95', 'TÉCNICO - QUADRA'],
  ['87', 'TÉCNICO - LARANJAL'],
  ['33', 'TÉCNICO - TAQUARITUBA'],
  ['55', 'TÉCNICO - ITAPEVA'],
  ['91', 'TÉCNICO - CONCHAS'],
  ['47', 'TÉCNICO - FARTURA'],
  ['59', 'TÉCNICO - ANHEMBI'],
  ['129', 'TÉCNICO - BOFETE'],
  ['57', 'TÉCNICO - BURI'],
  ['89', 'TÉCNICO - CERQUILHO'],
  ['121', 'TÉCNICO - CARAPICUÍBA'],
  ['113', 'TÉCNICO - CESÁRIO LANGE'],
  ['45', 'TÉCNICO - ITAÍ'],
  ['53', 'TÉCNICO - ITATINGA'],
  ['51', 'TÉCNICO - PARDINHO'],
  ['43', 'TÉCNICO - TAGUAÍ'],
  ['49', 'TÉCNICO - TAQUARIVAÍ'],
  ['93', 'TÉCNICO - TATUÍ'],
  ['283', 'TÉCNICO - OURO FINO'],
  ['291', 'TÉCNICO - BOITUVA'],
  ['123', 'TÉCNICO - IBAITI'],
  ['145', 'TÉCNICO - CIANORTE'],
  ['181', 'TÉCNICO - SANTO ANTONIO DA PLATINA'],
  ['177', 'TÉCNICO - ANDIRÁ'],
  ['155', 'TÉCNICO - IVAIPORÃ'],
  ['161', 'TÉCNICO - LONDRINA'],
  ['175', 'TÉCNICO - WENCESLAU BRAZ'],
  ['165', 'TÉCNICO - ARAPOTI'],
  ['179', 'TÉCNICO - CAMBARÁ'],
  ['185', 'TÉCNICO - BANDEIRANTES'],
  ['159', 'TÉCNICO - CAMBÉ'],
  ['215', 'TÉCNICO - CORNÉLIO PROCÓPIO'],
  ['149', 'TÉCNICO - ENGENHEIRO BELTRÃO'],
  ['151', 'TÉCNICO - GOIOERÊ'],
  ['207', 'TÉCNICO - IBIPORÃ'],
  ['205', 'TÉCNICO - IMBITUVA'],
  ['169', 'TÉCNICO - JAGUARIAÍVA'],
  ['203', 'TÉCNICO - MOREIRA SALES'],
  ['171', 'TÉCNICO - PRUDENTÓPOLIS'],
  ['157', 'TÉCNICO - QUINTA DO SOL'],
  ['241', 'TÉCNICO - ROLÂNDIA'],
  ['273', 'TÉCNICO - SANTA RITA'],
  ['255', 'TÉCNICO - CRUZÍLIA'],
  ['257', 'TÉCNICO - BAEPENDI'],
  ['259', 'TÉCNICO - CAXAMBU'],
  ['261', 'TÉCNICO - MINDURI'],
]);

const normalize = (value) => String(value || '')
  .normalize('NFD')
  .replace(/[\u0300-\u036f]/g, '')
  .toUpperCase()
  .replace(/\s+/g, ' ')
  .trim();

const CITY_SECTOR_RULES = Object.freeze({
  ITAI: (branch) => branch === '102' ? 'AVARE' : 'ITAI',
  PARANAPANEMA: (branch) => branch === '104' ? 'ITAPEVA' : 'AVARE',
  ITAPEVA: (branch) => branch === '3003' ? 'OURO FINO' : 'ITAPEVA',
  'WENCESLAU BRAZ': (branch) => branch === '3002' ? 'SANTA RITA' : 'WENCESLAU BRAZ',
  COTIA: 'OSASCO', OSASCO: 'OSASCO', 'SAO PAULO': 'OSASCO', BARUERI: 'OSASCO', CARAPICUIBA: 'CARAPICUIBA',
  AVARE: 'AVARE', 'AGUAS DE SANTA BARBARA': 'AVARE', ARANDU: 'AVARE', 'CERQUEIRA CESAR': 'AVARE', IARAS: 'AVARE', MANDURI: 'AVARE', OLEO: 'AVARE',
  FARTURA: 'FARTURA', SARUTAIA: 'FARTURA', 'BARAO DE ANTONINA': 'ITAPORANGA', 'CORONEL MACEDO': 'ITAPORANGA', ITAPORANGA: 'ITAPORANGA', RIVERSUL: 'ITAPORANGA',
  'SANTANA DO ITARARE': 'WENCESLAU BRAZ', TAGUAI: 'TAGUAI', TAQUARITUBA: 'TAQUARITUBA', TEJUPA: 'TAQUARITUBA', ANHEMBI: 'ANHEMBI', BOFETE: 'PARDINHO', PARDINHO: 'PARDINHO',
  ITATINGA: 'ITATINGA', BURI: 'BURI', 'CAPAO BONITO': 'ITAPEVA', ITABERA: 'ITAPEVA', 'NOVA CAMPINA': 'ITAPEVA', TAQUARIVAI: 'ITAPEVA',
  'LARANJAL PAULISTA': 'LARANJAL', LARANJAL: 'LARANJAL', JUMIRIM: 'LARANJAL', TIETE: 'LARANJAL', 'CESARIO LANGE': 'CERQUILHO', CERQUILHO: 'CERQUILHO',
  GUAREI: 'QUADRA', QUADRA: 'QUADRA', 'TORRE DE PEDRA': 'QUADRA', PORANGABA: 'QUADRA', TATUI: 'TATUI', PEREIRAS: 'CONCHAS', CONCHAS: 'CONCHAS',
  IBAITI: 'IBAITI', PINHALAO: 'IBAITI', JAPIRA: 'IBAITI', TOMAZINA: 'IBAITI', 'CONSELHEIRO MAIRINK': 'IBAITI', 'JUNDIAI DO SUL': 'IBAITI', CONGONHINHAS: 'IBAITI', 'RIBEIRAO DO PINHAL': 'IBAITI',
  BANDEIRANTES: 'BANDEIRANTES', 'CORNELIO PROCOPIO': 'CORNELIO PROCOPIO', ANDIRA: 'ANDIRA', 'BARRA DO JACARE': 'ANDIRA', CAMBARA: 'CAMBARA', 'SANTO ANTONIO DA PLATINA': 'SANTO ANTONIO DA PLATINA',
  CAMBE: 'CAMBE', LONDRINA: 'LONDRINA', ROLANDIA: 'ROLANDIA', MARINGA: 'LONDRINA', ARAPOTI: 'ARAPOTI', JAGUARIAIVA: 'JAGUARIAIVA', PRUDENTOPOLIS: 'PRUDENTOPOLIS', IMBITUVA: 'IMBITUVA',
  GOIOERE: 'GOIOERE', JAPURA: 'CIANORTE', 'SAO MANOEL DO PARANA': 'CIANORTE', CIANORTE: 'CIANORTE', 'MOREIRA SALES': 'MOREIRA SALES', 'ENGENHEIRO BELTRAO': 'ENGENHEIRO BELTRAO',
  'QUINTA DO SOL': 'QUINTA DO SOL', IVAIPORA: 'IVAIPORA', 'JARDIM ALEGRE': 'IVAIPORA', CAXAMBU: 'CAXAMBU', MINDURI: 'MINDURI', BAEPENDI: 'BAEPENDI', CRUZILIA: 'CRUZILIA', CARRANCAS: 'CRUZILIA',
  'SANTA RITA DO SAPUCAI': 'SANTA RITA', MACHADO: 'SANTA RITA', ITAJUBA: 'SANTA RITA', 'MARIA DA FE': 'SANTA RITA', PIRANGUINHO: 'SANTA RITA', 'SAO JOSE DO ALEGRE': 'SANTA RITA',
  'AGUAS DE LINDOIA': 'OURO FINO', ITAPIRA: 'OURO FINO', ALBERTINA: 'OURO FINO', 'BOM REPOUSO': 'OURO FINO', 'BORDA DA MATA': 'OURO FINO', 'BRAGANCA PAULISTA': 'OURO FINO',
  'BUENO BRANDAO': 'OURO FINO', EXTREMA: 'OURO FINO', INCONFIDENTES: 'OURO FINO', JACUTINGA: 'OURO FINO', LINDOIA: 'OURO FINO', 'MONTE SIAO': 'OURO FINO', MUNHOZ: 'OURO FINO',
  'OURO FINO': 'OURO FINO', 'PEDRA BELA': 'OURO FINO', 'POUSO ALEGRE': 'OURO FINO', 'SENADOR AMARAL': 'OURO FINO', 'SERRA NEGRA': 'OURO FINO', TOLEDO: 'OURO FINO',
  BOITUVA: 'BOITUVA', SOROCABA: 'BOITUVA', ALAMBARI: 'BOITUVA', IPERO: 'BOITUVA', 'CAPELA DO ALTO': 'BOITUVA', 'SANTANA DE PARNAIBA': 'BOITUVA',
});

export const findIxcSectorSuggestion = (city, branch) => {
  const cityKey = normalize(city);
  const rule = CITY_SECTOR_RULES[cityKey];
  const alias = typeof rule === 'function' ? rule(String(branch || '').trim()) : rule;
  if (!alias) return null;
  const aliasKey = normalize(alias);
  const match = IXC_SECTOR_OPTIONS.find(([, title]) => normalize(title).replace(/^TECNICO\s*-\s*/, '') === aliasKey);
  return match ? { code: match[0], title: match[1] } : null;
};
